version: '3.8'

services:
  bootstrap:
    build: .
    command: ./bin/bootstrap --port=8080
    ports:
      - "8080:8080"
    volumes:
      - ./data/bootstrap:/data
    networks:
      - zk-network

  coordinator:
    build: .
    command: >
      ./bin/peer 
      --name=coordinator 
      --port=9001 
      --coordinator 
      --zk 
      --zkdb=/data/zk 
      --bootstrap=http://bootstrap:8080
    ports:
      - "9001:9001"
    volumes:
      - ./data/coordinator:/data
    depends_on:
      - bootstrap
    networks:
      - zk-network

  worker-1:
    build: .
    command: >
      ./bin/peer 
      --name=worker-1 
      --port=9101 
      --worker 
      --zk 
      --zkdb=/data/zk 
      --bootstrap=http://bootstrap:8080
    volumes:
      - ./data/worker-1:/data
    depends_on:
      - bootstrap
    networks:
      - zk-network
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '2'
          memory: 4G

  simulator:
    build: .
    command: >
      ./bin/simulator 
      --coordinator=coordinator:9001 
      --tps=50 
      --batch-size=100 
      --fraud-rate=0.02 
      --duration=0
    depends_on:
      - coordinator
      - worker-1
    networks:
      - zk-network

  monitor:
    build: .
    command: ./scripts/monitor.sh
    environment:
      - BOOTSTRAP_URL=http://bootstrap:8080
      - COORDINATOR_URL=http://coordinator:9001
    depends_on:
      - coordinator
    networks:
      - zk-network

networks:
  zk-network:
    driver: bridge

volumes:
  zk-data: