version: "3.9"

services:
  # Bootstrap server for peer discovery
  bootstrap:
    build: .
    command: ["bootstrap", "--port=8080"]
    ports:
      - "8080:8080"
    networks:
      - p2pnet
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Coordinator node
  coordinator:
    build: .
    command: [
      "--name=coordinator",
      "--port=9001", 
      "--coordinator",
      "--bootstrap=http://bootstrap:8080",
      "--auto-demo"
    ]
    depends_on:
      bootstrap:
        condition: service_healthy
    ports:
      - "9001:9001"
    networks:
      - p2pnet
    environment:
      - PEER_ROLE=coordinator

  # Worker nodes
  worker1:
    build: .
    command: [
      "--name=worker-1",
      "--port=9002", 
      "--worker",
      "--bootstrap=http://bootstrap:8080"
    ]
    depends_on:
      bootstrap:
        condition: service_healthy
    ports:
      - "9002:9002"
    networks:
      - p2pnet
    environment:
      - PEER_ROLE=worker

  # worker2:
  #   build: .
  #   command: [
  #     "--name=worker-2",
  #     "--port=9003", 
  #     "--worker",
  #     "--bootstrap=http://bootstrap:8080"
  #   ]
  #   depends_on:
  #     bootstrap:
  #       condition: service_healthy
  #   ports:
  #     - "9003:9003"
  #   networks:
  #     - p2pnet
  #   environment:
  #     - PEER_ROLE=worker

  # worker3:
  #   build: .
  #   command: [
  #     "--name=worker-3",
  #     "--port=9004", 
  #     "--worker",
  #     "--bootstrap=http://bootstrap:8080"
  #   ]
  #   depends_on:
  #     bootstrap:
  #       condition: service_healthy
  #   ports:
  #     - "9004:9004"
  #   networks:
  #     - p2pnet
  #   environment:
  #     - PEER_ROLE=worker

  # worker4:
  #   build: .
  #   command: [
  #     "--name=worker-4",
  #     "--port=9005", 
  #     "--worker",
  #     "--bootstrap=http://bootstrap:8080"
  #   ]
  #   depends_on:
  #     bootstrap:
  #       condition: service_healthy
  #   ports:
  #     - "9005:9005"
  #   networks:
  #     - p2pnet
  #   environment:
  #     - PEER_ROLE=worker

networks:
  p2pnet:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  bootstrap_data: